title: Futureproofs
email: info@wearefutureproofs.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.wearefutureproofs.com"
twitter_username: john_pettigrew
github_username:  johnpettigrew

# Build settings
# theme: minima
plugins:
  - jekyll-feed

sass:
  load_paths:
    - _sass
    - node_modules/

theme: jekyll-theme-minimal