title: Futureproofs
email: info@wearefutureproofs.com
description: >- # this means to ignore newlines until "baseurl:"
  Communication, on-screen proofing and editorial project management software
  for people and team who create high-quality illustrated books.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.wearefutureproofs.com"
twitter_username: john_pettigrew
github_username:  johnpettigrew

plugins:
  - jekyll-gzip

sass:
  load_paths:
    - _sass
    - node_modules/
